on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm ci
      - run: npm start
        env:
          GITHUB_ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ORGANISATION: ${{secrets.ORGANISATION}}
          MONGO_URL: ${{secrets.MONGO_URL}}
          SMTP_URL: ${{secrets.SMTP_URL}}
          EMAIL_FROM: ${{secrets.EMAIL_FROM}}
          EMAIL_TO: ${{secrets.EMAIL_TO}}
